### ISSUE TITLE
convert into cli

### ISSUE THREAD

**Issue by gaurav-gogia** [gaurav-gogia/dfis-utils#2]
Each folder has its own main package file. I was wondering if a simple CLI added for each so that they could be run more easily. More details can be discussed in this thread. 

I get that my above description is a bit vague but its just that I couldn't find better words. I'll try my best to answer your queries though

**Comment by ibraimgm** [comment]
Do you prefer (1) one binary per folder or (2) a single cli that allows access to all tools?

Personally, I think a single cli with all commands works best, we can have something like:
```
$ dfis hash myfile.txt
MD5: ACBD18DB4CC2F85CEDEF654FCCC4A4D8 # same as crypto-utils/hash-big.go

$ dfis hash --all myfile.txt # same as crypto-utils/hash-small.go
MD5: ACBD18DB4CC2F85CEDEF654FCCC4A4D8
SHA1: ...
SHA256: ...
SHA512: ...

$ dfis info myfile.txt # same as file-utils/file-info.go
.... you get the idea ...
```

If this is what you want, I can work on it using [a library that I recently wrote](https://github.com/ibraimgm/libcmd) just for this kind of scenario.

**Comment by ibraimgm** [comment]
Also, as an unrelated note, I can convert this project to go modules if you want.

**Comment by gaurav-gogia** [comment]
Hey! 

Yea, second option sounds better. I didn't want to go for it because it felt a bit too complex but if we can make it happen then that would be awesome. 

Also, yes go modules will be cool too. I don't know why but I keep running into weird errors like "this file is not a part of X package" while it actually is when I try using go modules.

**Comment by ibraimgm** [comment]
Done, take a look at PR #10 and see if it is good enough. If/when it is approved, I will start the main cli application.

Also, I added Issue #11.

**Comment by gaurav-gogia** [comment]
That was fast! Alright, will look into it and update you :)

**Comment by ibraimgm** [comment]
@gaurav-gogia , check PR #15 to see if it is acceptable or if you have any other suggestions.

**Comment by gaurav-gogia** [comment]
Sure, will look into it now :)
